setwd("e:/Coursera/Work/Data-R/")
x<-read.table("household_power_consumption.txt",sep=';',header = TRUE,na.strings = "?")
x$Date <- as.Date(x$Date, format = "%d/%m/%Y")
y<-subset(x,subset=(Date>="2007-02-01" & Date<="2007-02-02"))
y1<-paste(y$Date,y$Time)
y$Datetime<-as.POSIXct(y1)
plot3<-with(y,{plot(y$Sub_metering_1 ~y$Datetime,type="l",ylab="Global Active Power (kilowatts)",xlab="")
lines(y$Sub_metering_2~y$Datetime,col="Red")
lines(y$Sub_metering_3~y$Datetime,col="Blue")})
legend("topright",col = c("Black","Red","Blue"),lty=1,lwd=2,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()