setwd("e:/Coursera/Work/Data-R/")
x<-read.table("household_power_consumption.txt",sep=';',header = TRUE,na.strings = "?")
x$Date <- as.Date(x$Date, format = "%d/%m/%Y")
y<-subset(x,subset=(Date>="2007-02-01" & Date<="2007-02-02"))
y1<-paste(y$Date,y$Time)
y$Datetime<-as.POSIXct(y1)
plot2<-plot(y$Global_active_power~y$Datetime,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.copy(png,file="plot2.png")
dev.off()