setwd("e:/Coursera/Work/Data-R/")
x<-read.table("household_power_consumption.txt",sep=';',header = TRUE,na.strings = "?")
x$Date <- as.Date(x$Date, format = "%d/%m/%Y")
y<-subset(x,subset=(Date>="2007-02-01" & Date<="2007-02-02"))
y1<-paste(y$Date,y$Time)
y$Datetime<-as.POSIXct(y1)
par(mfrow=c(2,2),mar=c(4,4,2,1),oma=c(0,0,2,0))
plot4<-with(y,{plot(y$Global_active_power~y$Datetime,type="l",ylab="Global Actvive Power",xlab="")
  plot(y$Voltage~y$Datetime,type="l",ylab="Voltage",xlab="")
  plot(y$Sub_metering_1 ~y$Datetime,type="l",ylab="Global Active Power (kilowatts)",xlab="Energy sub metering")
  lines(y$Sub_metering_2~y$Datetime,col="Red")
  lines(y$Sub_metering_3~y$Datetime,col="Blue")})
legend("topright",col=c("Black","Red","Blue"),lty = 1,lwd=2,legend = c("Submetering1","Submetering2","Submetering3"))
plot(y$Global_reactive_power~y$Datetime,type="l",ylab="Global_rective_power",xlab="datetime")
dev.copy(png,file="Plot4.png")
dev.off()